name: Update Project Work Estimations

on:
  schedule:
    - cron: '*/20 * * * *'  # Every 20 minutes

  workflow_dispatch:

jobs:
  update_estimates:

    if: true   # Toggle between true/false to enable/disable this workflow

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4        

      - name: Install dependencies
        run: npm install axios

      - name: Run update-project-item-estimation script
        env:
          TOKEN_TARGET_PROJECT_RW: ${{ secrets.TOKEN_TARGET_PROJECT_RW }}          
          VAR_TARGET_PROJECT_OWNER_TYPE: ${{ vars.VAR_TARGET_PROJECT_OWNER_TYPE }}
          VAR_TARGET_PROJECT_OWNER_NAME: ${{ vars.VAR_TARGET_PROJECT_OWNER_NAME }}
          VAR_TARGET_PROJECT_NUMBER_ID: ${{ vars.VAR_TARGET_PROJECT_NUMBER_ID }}

        run: node .github/scripts/update-project-item-estimation.js
